# Ressource Provisioning is done in create-ressources.azcli od T03-Demo05
pool:  
  vmImage: 'ubuntu-latest'  
trigger:
  branches:
    include:   
    - master
    - development
  paths:
    include:
      - FoodApi/*          
variables:
  buildConfiguration: 'Release'
  apiPath: 'FoodApi/'
  rg: 'az400-t03-deploydocker-25315'
  dockerReg: 'azDocker'  
  conARM: 'scDocker'
  acr: 'az400cr25315'
  imageName: 'foodapi'
  appService: 'az400-foodservice'

stages:
  - stage: 'BuildApi'
    displayName: 'Build Api Image'
    jobs:      
      - job: "Build"      
        steps:
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerReg)        
          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: $(apiPath)/app.prod.dockerfile        
          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(dockerReg)

  # Use a template with vars here - does not make any sense - just on tast an 5 params
  - stage: 'DeployApi'
    displayName: 'Deploy Api Container'
    jobs:      
      - job: 'Deploy'
        steps: 
          - template: apideploy.yml
            parameters:
              conARM: $(conARM)
              appService: $(appService)
              rg: $(rg)
              acr: $(acr)
              imageName: $(imageName)          

  # Original Step
                
  # - stage: 'DeployApi'
  #   displayName: 'Deploy Api Container'
  #   jobs:      
  #     - job: 'Deploy'
  #       steps:          
  #         - task: AzureWebAppContainer@1
  #           inputs:
  #             azureSubscription: $(conARM)
  #             appName: $(appService)
  #             deployToSlotOrASE: true
  #             resourceGroupName: $(rg)
  #             slotName: 'production'
  #             containers: '$(acr).azurecr.io/$(imageName)'          