apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodapp
  template:
    metadata:
      labels:
        app: foodapp                 
    spec:
      containers:
      - name: foodui
        image: arambazamba/foodui
        imagePullPolicy: Always
        ports:
        - containerPort: 80        
        resources:
          limits:            
            cpu: "500m"
            memory: "128Mi"