name: .Net Core Api to Azure Web App

on:
  push:
    branches:
      - master
    paths:
      - "FoodApi/**"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Build with dotnet
        run: dotnet build ${{ github.workspace }}/FoodApi/FoodApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ github.workspace }}/FoodApi/FoodApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "foodapi-007"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f7a76ffccc534965a5ff8ff25ac844df }}
          package: ${{env.DOTNET_ROOT}}/myapp
