name: Kubernetes Deploy
pool:
  vmImage: "ubuntu-20.04"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodApi/*

variables:
  dockerReg: "Container Registry Connection"
  imageName: "foodapi"
  acr: "az400m16reg.azurecr.io"
  tag: "$(Build.BuildId)"
  kube: "Kubernetes Cluster Connection"
  ns: "default"
  imagePullSecret: "secret"

stages:
  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        environment: "spike.default"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: createSecret
                    secretName: $(imagePullSecret)
                    dockerRegistryEndpoint: $(dockerReg)
                    kubernetesServiceConnection: $(kube)
                    namespace: $(ns)

                - task: CmdLine@2
                  inputs:
                    script: "dir"

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: "deploy"
                    kubernetesServiceConnection: $(kube)
                    manifests: |
                      $(Build.ArtifactStagingDirectory)/manifests/foodservice.yml
                    imagePullSecrets: $(imagePullSecret)
                    containers: "$(acr)/$(imageName):$(tag)"
