trigger:
  - master

variables:
  dockerReg: "conDockerReg"
  imageName: "foodapi"
  acr: "integrationsonline.azurecr.io"
  tag: "$(Build.BuildId)"
  kube: "conKube"
  ns: "foodapp-prod"
  imagePullSecret: "secret"

stages:
  - stage: Deploy
    displayName: Deploy stage

    jobs:
      - deployment: Deploy
        displayName: Deploy Job
        pool:
          vmImage: $(vmImageName)
        environment: Dev.foodapp-prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: createSecret
                    secretName: $(imagePullSecret)
                    dockerRegistryEndpoint: $(dockerReg)
                    kubernetesServiceConnection: $(kube)
                    namespace: 'foodapp-prod'

                - task: KubernetesManifest@0
                  displayName: Deploy to Kubernetes cluster
                  inputs:
                    action: "deploy"
                    kubernetesServiceConnection: $(kube)
                    manifests: |
                      $(Pipeline.Workspace)/manifests/foodservice.yml
                    imagePullSecrets: $(imagePullSecret)
                    containers: "$(acr)/$(imageRepository):$(tag)"
