name: FoodApi Docker Build
pool:
  vmImage: "ubuntu-20.04"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - FoodApi/*

variables:
  buildConfiguration: "Release"
  apiPath: "FoodApi/"
  dockerReg: "conM15"
  imageName: "foodapi"
  appService: "foodapi-21482"
   

stages:
  - stage: "BuildApi"
    displayName: "Build Api Image"
    jobs:
      - job: "Build"
        steps:
        

          - bash: echo "##vso[task.setvariable variable=tags]git tag --sort=-creatordate";
            
          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(dockerReg)

          - task: Docker@2
            displayName: Build and Push
            inputs:
              repository: "$(imageName)"
              command: "buildAndPush"
              Dockerfile: "FoodApi/dockerfile"
              tags: "$(tag)-$(Build.SourceBranchName)-$(Build.SourceVersion)"

          - task: Docker@2
            displayName: Logout of ACR
            inputs:
              command: logout
              containerRegistry: $(dockerReg)
