name: "food-api multistage build-deploy"

variables:
  dotnetSdkVersion: "5.x"
  buildConfiguration: Release
  releaseBranchName: master
  apifolder: FoodApi
  appservice: foodapi-900

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - $(apifolder)

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: "Build"
    displayName: "Build"
    jobs:
      - job: "Build"
        displayName: "Build job"

        steps:
          - task: UseDotNet@2
            displayName: "Use .NET Core SDK $(dotnetSdkVersion)"
            inputs:
              version: "$(dotnetSdkVersion)"

          - task: DotNetCoreCLI@2
            displayName: "Restore project dependencies"
            inputs:
              command: "restore"
              projects: "$(apifolder)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Build the project - $(buildConfiguration)"
            inputs:
              command: "build"
              arguments: "--no-restore --configuration $(buildConfiguration)"
              projects: "$(apifolder)/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Publish the project - $(buildConfiguration)"
            inputs:
              command: "publish"
              projects: "$(apifolder)/*.csproj"
              publishWebProjects: false
              arguments: "--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)"
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: "Deploy"
    displayName: "Deploy"
    dependsOn: Test

    jobs:
      - job: deploy_to_as

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "drop"
              downloadPath: "$(System.ArtifactsDirectory)"

          - task: AzureRmWebAppDeployment@4
            displayName: "Azure App Service Deploy: $(appservice)"
            inputs:
              ConnectionType: "AzureRM"
              azureSubscription: "Visual Studio Enterprise (78033352-805c-4acd-af80-f8f95083268d)"
              appType: "webApp"
              WebAppName: "$(appservice)"
              packageForLinux: "$(System.ArtifactsDirectory)/**/*.zip"
