name: spfx build

trigger:
  branches:
    include:
      - master
  paths:
    include:    
      - FoodListSPFx/*

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: |
      gulp clean
      gulp bundle --ship
      gulp package-solution --ship
    displayName: 'Build and Package Solution'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/sharepoint/solution/*.sppkg
      ArtifactName: SPFxPkg
      publishLocation: FilePath
      TargetPath: /var
    displayName: #Publish build SPFx artifacts'
