name: spfx build

variables:
  pkgName: sp-fx-alm

trigger:
  branches:
    include:
      - master
  paths:
    include:

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    name: "Install Node.js"

  - script: npm install
    name: "npm install"

  - script: |
      gulp clean
      gulp bundle --ship
      gulp package-solution --ship
    name: "Build and Package Solution"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/sharepoint/solution/$(pkgName).sppkg
      ArtifactName: SPFxPkg
      publishLocation: FilePath
      TargetPath: /var
    name: "Publish build SPFx artifacts"
