name: spfx build

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "FoodListSPFx/*"

stages:
  - stage: default
    jobs:
      - job: Job
        pool:
          vmImage: "ubuntu-20.04"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: 10.x
            displayName: Install Node.js
          - task: CmdLine@2
            displayName: npm install
            inputs:
              script: npm install
              
          - task: gulp@0
            displayName: "gulp bundel"            
            inputs:
              gulpFile: '$(Build.ArtifactStagingDirectory)/FoodListSPFx/gulpfile.js'
              targets: "bundle"
              arguments: "--ship"

          - task: gulp@1
            displayName: "gulp package solution"
            inputs:
              gulpFile: 'FoodListSPFx/gulpfile.js'
              targets: "package-solution"
              arguments: "--ship"

          - task: CopyFiles@2
            displayName: "Copy Files to: $(build.artifactstagingdirectory)/drop"
            inputs:
              Contents: "sharepoint/solution/*.sppkg"
              TargetFolder: "$(build.artifactstagingdirectory)/drop"

          - task: PublishBuildArtifacts@1
            displayName: "Publish artifacts: drop"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/drop"
